name: shell commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Daisy! My love! "
      - name: multiline script
        run:
          node -v
          npm -v